export const products = [
  // Chairs
  {
    id: 1,
    name: "Door",
    category: "Doors",
    price: 99,
    imageUrl: "door-1.jpeg",
    rating: 5,
  },
  {
    id: 2,
    name: "Classic Wooden Door",
    category: "Doors",
    price: 149,
    imageUrl: "door-2.jpeg",
    rating: 4,
  },
  {
    id: 3,
    name: "Modern Sliding Door",
    category: "Doors",
    price: 199,
    imageUrl: "door-3.jpeg",
    rating: 4.5,
  },
  {
    id: 4,
    name: "Rustic Barn Door",
    category: "Doors",
    price: 179,
    imageUrl: "door-4.jpeg",
    rating: 5,
  },
  {
    id: 5,
    name: "Glass Panel Door",
    category: "Doors",
    price: 249,
    imageUrl: "door-5.jpeg",
    rating: 4.2,
  },
  {
    id: 6,
    name: "Steel Security Door",
    category: "Doors",
    price: 299,
    imageUrl: "door-6.jpeg",
    rating: 4.8,
  },
  {
    id: 7,
    name: "French Double Doors",
    category: "Doors",
    price: 349,
    imageUrl: "door-7.jpeg",
    rating: 4.6,
  },
  {
    id: 8,
    name: "Decorative Entrance Door",
    category: "Doors",
    price: 399,
    imageUrl: "door-8.jpeg",
    rating: 4.7,
  },
  {
    id: 9,
    name: "PVC Folding Door",
    category: "Doors",
    price: 99,
    imageUrl: "door-9.jpeg",
    rating: 4.3,
  },
  {
    id: 10,
    name: "Elegant Wooden Door",
    category: "Doors",
    price: 229,
    imageUrl: "door-10.jpeg",
    rating: 4.5,
  },
  {
    id: 11,
    name: "Contemporary Glass Door",
    category: "Doors",
    price: 259,
    imageUrl: "door-11.jpeg",
    rating: 5,
  },
  {
    id: 12,
    name: "Minimalist White Door",
    category: "Doors",
    price: 139,
    imageUrl: "door-12.jpeg",
    rating: 4.4,
  },
  {
    id: 13,
    name: "Sliding Barn Door",
    category: "Doors",
    price: 189,
    imageUrl: "door-13.jpeg",
    rating: 4.8,
  },
  {
    id: 14,
    name: "Vintage Carved Door",
    category: "Doors",
    price: 399,
    imageUrl: "door-14.jpeg",
    rating: 4.9,
  },
  {
    id: 15,
    name: "Iron Gate Door",
    category: "Doors",
    price: 349,
    imageUrl: "door-15.jpeg",
    rating: 5,
  },
  {
    id: 16,
    name: "Oak Wood Door",
    category: "Doors",
    price: 249,
    imageUrl: "door-16.jpeg",
    rating: 4.3,
  },
  {
    id: 17,
    name: "Frosted Glass Door",
    category: "Doors",
    price: 279,
    imageUrl: "door-17.jpeg",
    rating: 4.7,
  },
  {
    id: 18,
    name: "Custom Panel Door",
    category: "Doors",
    price: 219,
    imageUrl: "door-18.jpeg",
    rating: 4.5,
  },
  {
    id: 19,
    name: "Hardwood Patio Door",
    category: "Doors",
    price: 499,
    imageUrl: "door-19.jpeg",
    rating: 5,
  },
  {
    id: 20,
    name: "Antique Wooden Door",
    category: "Doors",
    price: 349,
    imageUrl: "door-20.jpeg",
    rating: 4.8,
  },
  {
    id: 21,
    name: "Rustic Wooden Door",
    category: "Doors",
    price: 279,
    imageUrl: "door-21.jpeg",
    rating: 4.6,
  },
  {
    id: 22,
    name: "Double Sliding Door",
    category: "Doors",
    price: 399,
    imageUrl: "door-22.jpeg",
    rating: 4.9,
  },
  {
    id: 23,
    name: "Steel Reinforced Door",
    category: "Doors",
    price: 459,
    imageUrl: "door-23.jpeg",
    rating: 4.7,
  },
  {
    id: 24,
    name: "Elegant Glass Door",
    category: "Doors",
    price: 329,
    imageUrl: "door-24.jpeg",
    rating: 4.5,
  },
  {
    id: 25,
    name: "Solid Core Door",
    category: "Doors",
    price: 299,
    imageUrl: "door-25.jpeg",
    rating: 5,
  },
  {
    id: 26,
    name: "Mahogany Entry Door",
    category: "Doors",
    price: 449,
    imageUrl: "door-26.jpeg",
    rating: 4.6,
  },
  {
    id: 27,
    name: "Panel Interior Door",
    category: "Doors",
    price: 179,
    imageUrl: "door-27.jpeg",
    rating: 4.4,
  },
  {
    id: 28,
    name: "Aluminum Sliding Door",
    category: "Doors",
    price: 499,
    imageUrl: "door-28.jpeg",
    rating: 5,
  },
  {
    id: 29,
    name: "Walnut Veneer Door",
    category: "Doors",
    price: 389,
    imageUrl: "door-29.jpeg",
    rating: 4.9,
  },
  {
    id: 30,
    name: "Custom French Doors",
    category: "Doors",
    price: 599,
    imageUrl: "door-30.jpeg",
    rating: 4.8,
  },
  {
    id: 31,
    name: "Solid Metal Door",
    category: "Doors",
    price: 349,
    imageUrl: "door-31.jpeg",
    rating: 5,
  },
  {
    id: 32,
    name: "Louvered Closet Door",
    category: "Doors",
    price: 119,
    imageUrl: "door-32.jpeg",
    rating: 4.2,
  },
  {
    id: 33,
    name: "Elegant Patio Door",
    category: "Doors",
    price: 419,
    imageUrl: "door-33.jpeg",
    rating: 4.7,
  },
  {
    id: 34,
    name: "Textured Glass Door",
    category: "Doors",
    price: 329,
    imageUrl: "door-34.jpeg",
    rating: 4.8,
  },
  {
    id: 35,
    name: "Eco-friendly Door",
    category: "Doors",
    price: 279,
    imageUrl: "door-35.jpeg",
    rating: 4.4,
  },
  {
    id: 36,
    name: "Pine Panel Door",
    category: "Doors",
    price: 199,
    imageUrl: "door-36.jpeg",
    rating: 4.5,
  },
  {
    id: 37,
    name: "Reinforced Security Door",
    category: "Doors",
    price: 599,
    imageUrl: "door-37.jpeg",
    rating: 4.9,
  },
  {
    id: 38,
    name: "Modern Frosted Door",
    category: "Doors",
    price: 249,
    imageUrl: "door-38.jpeg",
    rating: 4.7,
  },
  {
    id: 39,
    name: "Hardwood French Door",
    category: "Doors",
    price: 469,
    imageUrl: "door-39.jpeg",
    rating: 5,
  },
  {
    id: 40,
    name: "Minimal Sliding Door",
    category: "Doors",
    price: 319,
    imageUrl: "door-40.jpeg",
    rating: 4.8,
  },
  {
    id: 41,
    name: "Vinyl Closet Door",
    category: "Doors",
    price: 129,
    imageUrl: "door-41.jpeg",
    rating: 4.2,
  },
  {
    id: 42,
    name: "Premium Oak Door",
    category: "Doors",
    price: 249,
    imageUrl: "door-42.jpeg",
    rating: 4.5,
  },
  {
    id: 43,
    name: "Industrial Metal Door",
    category: "Doors",
    price: 399,
    imageUrl: "door-43.jpeg",
    rating: 4.9,
  },
  {
    id: 44,
    name: "Wooden Cottage Door",
    category: "Doors",
    price: 349,
    imageUrl: "door-44.jpeg",
    rating: 4.6,
  },
  {
    id: 45,
    name: "Fire-resistant Door",
    category: "Doors",
    price: 599,
    imageUrl: "door-45.jpeg",
    rating: 5,
  },
  {
    id: 46,
    name: "Glass Sliding Door",
    category: "Doors",
    price: 449,
    imageUrl: "door-46.jpeg",
    rating: 4.8,
  },
  {
    id: 47,
    name: "Classic White Door",
    category: "Doors",
    price: 179,
    imageUrl: "door-47.jpeg",
    rating: 4.3,
  },
  {
    id: 48,
    name: "Eco-smart Door",
    category: "Doors",
    price: 329,
    imageUrl: "door-48.jpeg",
    rating: 4.7,
  },
  {
    id: 49,
    name: "Architectural Door",
    category: "Doors",
    price: 499,
    imageUrl: "door-49.jpeg",
    rating: 4.9,
  },
  {
    id: 50,
    name: "Carved Teak Door",
    category: "Doors",
    price: 549,
    imageUrl: "door-50.jpeg",
    rating: 5,
  },

  // Beds

  {
    id: 51,
    name: "Executive Director's Table",
    category: "Director's Table",
    price: 499,
    imageUrl: "d-1.jpeg",
    rating: 5,
  },
  {
    id: 52,
    name: "Modern Director's Desk",
    category: "Director's Table",
    price: 429,
    imageUrl: "d-2.jpeg",
    rating: 4.8,
  },
  {
    id: 53,
    name: "L-Shaped Director's Table",
    category: "Director's Table",
    price: 549,
    imageUrl: "d-3.jpeg",
    rating: 4.7,
  },
  {
    id: 54,
    name: "Glass Top Director's Table",
    category: "Director's Table",
    price: 599,
    imageUrl: "d-4.jpeg",
    rating: 4.5,
  },
  {
    id: 55,
    name: "Wooden Director's Desk",
    category: "Director's Table",
    price: 469,
    imageUrl: "d-5.jpeg",
    rating: 5,
  },
  {
    id: 56,
    name: "Compact Director's Table",
    category: "Director's Table",
    price: 399,
    imageUrl: "d-6.jpeg",
    rating: 4.2,
  },
  {
    id: 57,
    name: "Ergonomic Director's Desk",
    category: "Director's Table",
    price: 659,
    imageUrl: "d-7.jpeg",
    rating: 4.9,
  },
  {
    id: 58,
    name: "Minimalist Director's Table",
    category: "Director's Table",
    price: 429,
    imageUrl: "d-8.jpeg",
    rating: 4.4,
  },
  {
    id: 59,
    name: "Luxury Director's Table",
    category: "Director's Table",
    price: 749,
    imageUrl: "d-9.jpeg",
    rating: 5,
  },
  {
    id: 60,
    name: "Adjustable Director's Desk",
    category: "Director's Table",
    price: 519,
    imageUrl: "d-10.jpeg",
    rating: 4.7,
  },
  {
    id: 61,
    name: "Classic Director's Table",
    category: "Director's Table",
    price: 469,
    imageUrl: "d-11.jpeg",
    rating: 4.8,
  },
  {
    id: 62,
    name: "Sleek Director's Table",
    category: "Director's Table",
    price: 499,
    imageUrl: "d-12.jpeg",
    rating: 4.6,
  },
  {
    id: 63,
    name: "Contemporary Director's Desk",
    category: "Director's Table",
    price: 559,
    imageUrl: "d-13.jpeg",
    rating: 4.5,
  },
  {
    id: 64,
    name: "Large Director's Table",
    category: "Director's Table",
    price: 679,
    imageUrl: "d-14.jpeg",
    rating: 5,
  },
  {
    id: 65,
    name: "Versatile Director's Desk",
    category: "Director's Table",
    price: 529,
    imageUrl: "d-15.jpeg",
    rating: 4.9,
  },
  {
    id: 66,
    name: "Premium Director's Desk",
    category: "Director's Table",
    price: 629,
    imageUrl: "d-16.jpeg",
    rating: 5,
  },
  {
    id: 67,
    name: "Modern Glass Director's Table",
    category: "Director's Table",
    price: 649,
    imageUrl: "d-17.jpeg",
    rating: 4.6,
  },
  {
    id: 68,
    name: "Simple Director's Desk",
    category: "Director's Table",
    price: 429,
    imageUrl: "d-18.jpeg",
    rating: 4.3,
  },
  {
    id: 69,
    name: "Stylish Director's Table",
    category: "Director's Table",
    price: 589,
    imageUrl: "d-19.jpeg",
    rating: 4.7,
  },
  {
    id: 70,
    name: "Elegant Director's Desk",
    category: "Director's Table",
    price: 479,
    imageUrl: "d-20.jpeg",
    rating: 4.8,
  },

  // Sofas
  {
    id: 71,
    name: "Boss Table",
    category: "Boss Table",
    price: 499,
    imageUrl: "b-1.jpeg",
    rating: 4,
  },
  {
    id: 72,
    name: "Executive Boss Table",
    category: "Boss Table",
    price: 599,
    imageUrl: "b-2.jpeg",
    rating: 4.5,
  },
  {
    id: 73,
    name: "Modern Boss Desk",
    category: "Boss Table",
    price: 649,
    imageUrl: "b-3.jpeg",
    rating: 5,
  },
  {
    id: 74,
    name: "Classic Wooden Desk",
    category: "Boss Table",
    price: 579,
    imageUrl: "b-4.jpeg",
    rating: 4.8,
  },
  {
    id: 75,
    name: "Ergonomic Office Table",
    category: "Boss Table",
    price: 699,
    imageUrl: "b-5.jpeg",
    rating: 4.7,
  },
  {
    id: 76,
    name: "Luxury Boss Table",
    category: "Boss Table",
    price: 799,
    imageUrl: "b-6.jpeg",
    rating: 5,
  },
  {
    id: 77,
    name: "Compact Boss Desk",
    category: "Boss Table",
    price: 449,
    imageUrl: "b-7.jpeg",
    rating: 4.2,
  },
  {
    id: 78,
    name: "Minimalist Boss Desk",
    category: "Boss Table",
    price: 529,
    imageUrl: "b-8.jpeg",
    rating: 4.5,
  },
  {
    id: 79,
    name: "Industrial Style Table",
    category: "Boss Table",
    price: 609,
    imageUrl: "b-9.jpeg",
    rating: 4.3,
  },
  {
    id: 80,
    name: "Premium Wooden Desk",
    category: "Boss Table",
    price: 679,
    imageUrl: "b-10.jpeg",
    rating: 4.9,
  },
  {
    id: 81,
    name: "Adjustable Boss Table",
    category: "Boss Table",
    price: 749,
    imageUrl: "b-11.jpeg",
    rating: 4.6,
  },
  {
    id: 82,
    name: "Corner Boss Desk",
    category: "Boss Table",
    price: 829,
    imageUrl: "b-12.jpeg",
    rating: 5,
  },
  {
    id: 83,
    name: "Elegant Boss Desk",
    category: "Boss Table",
    price: 579,
    imageUrl: "b-13.jpeg",
    rating: 4.8,
  },
  {
    id: 84,
    name: "Spacious Boss Table",
    category: "Boss Table",
    price: 699,
    imageUrl: "b-14.jpeg",
    rating: 4.7,
  },
  // kitchen
  {
    id: 85,
    name: "Modern Kitchen",
    category: "kitchen",
    price: 49,
    imageUrl: "k-1.jpeg",
    rating: 5,
  },
  {
    id: 86,
    name: "Classic Kitchen ",
    category: "kitchen",
    price: 59,
    imageUrl: "k-2.jpeg",
    rating: 4,
  },
  {
    id: 87,
    name: "Wooden Kitchen",
    category: "kitchen",
    price: 69,
    imageUrl: "k-3.jpeg",
    rating: 3,
  },
  {
    id: 88,
    name: "Industrial Kitchen Floor",
    category: "kitchen",
    price: 89,
    imageUrl: "k-4.jpeg",
    rating: 5,
  },
  {
    id: 89,
    name: "Vintage Kitchen",
    category: "kitchen",
    price: 79,
    imageUrl: "k-5.jpeg",
    rating: 4,
  },
  {
    id: 90,
    name: "Contemporary Kitchen Floor",
    category: "kitchen",
    price: 99,
    imageUrl: "k-6.jpeg",
    rating: 5,
  },
];
